<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="userloveAdmin.loginTestCase.LoginWithValidCredential">
        <methods>
          <include name="verifyUserloginwithcorrectCredentials"/>
          <include name="afterMethod"/>
          <include name="setup"/>
          <include name="cleanUp"/>
          <include name="preSetup"/>
          <include name="postCleanUp"/>
        </methods>
      </class> <!-- userloveAdmin.loginTestCase.LoginWithValidCredential -->
      <class name="userloveAdmin.loginTestCase.LoginWithINVALIDCredential">
        <methods>
          <include name="afterMethod"/>
          <include name="verifyUserloginwithINVALIDCredentials"/>
          <include name="setup"/>
          <include name="cleanUp"/>
          <include name="postCleanUp"/>
          <include name="preSetup"/>
        </methods>
      </class> <!-- userloveAdmin.loginTestCase.LoginWithINVALIDCredential -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
